import { Account, Category, Transaction } from '@/types/finance';

export const DEFAULT_ACCOUNTS: Account[] = [
  {
    id: 'acc-bca',
    name: 'BCA Prioritas',
    type: 'bank',
    balance: 14500000,
    color: '#0060AF',
    icon: 'Landmark',
    account_number: '1280928371',
  },
  {
    id: 'acc-mandiri',
    name: 'Mandiri Livin',
    type: 'bank',
    balance: 5200000,
    color: '#003366',
    icon: 'CreditCard',
    account_number: '13700192837',
  },
  {
    id: 'acc-cash',
    name: 'Uang Tunai (Dompet)',
    type: 'cash',
    balance: 750000,
    color: '#10B981',
    icon: 'Banknote',
  },
  {
    id: 'acc-gopay',
    name: 'GoPay',
    type: 'ewallet',
    balance: 320000,
    color: '#00AED6',
    icon: 'Smartphone',
  },
  {
    id: 'acc-ovo',
    name: 'OVO',
    type: 'ewallet',
    balance: 180000,
    color: '#4C3494',
    icon: 'Smartphone',
  },
  {
    id: 'acc-shopeepay',
    name: 'ShopeePay',
    type: 'ewallet',
    balance: 245000,
    color: '#EE4D2D',
    icon: 'Smartphone',
  },
  {
    id: 'acc-bibit',
    name: 'Bibit / Reksadana',
    type: 'investment',
    balance: 25000000,
    color: '#059669',
    icon: 'TrendingUp',
  },
];

export const DEFAULT_CATEGORIES: Category[] = [
  // Expense
  { id: 'cat-food', name: 'Makanan & Minuman', type: 'expense', icon: 'UtensilsCrossed', color: '#F97316' },
  { id: 'cat-transport', name: 'Transportasi & Bensin', type: 'expense', icon: 'Car', color: '#3B82F6' },
  { id: 'cat-groceries', name: 'Belanja & Kebutuhan', type: 'expense', icon: 'ShoppingBag', color: '#EC4899' },
  { id: 'cat-bills', name: 'Tagihan, Listrik & Wifi', type: 'expense', icon: 'Zap', color: '#EAB308' },
  { id: 'cat-entertainment', name: 'Hiburan & Liburan', type: 'expense', icon: 'Film', color: '#8B5CF6' },
  { id: 'cat-health', name: 'Kesehatan & Obat', type: 'expense', icon: 'HeartPulse', color: '#EF4444' },
  { id: 'cat-education', name: 'Edukasi & Kursus', type: 'expense', icon: 'GraduationCap', color: '#06B6D4' },
  { id: 'cat-charity', name: 'Zakat, Infaq & Sedekah', type: 'expense', icon: 'HandHeart', color: '#14B8A6' },
  { id: 'cat-other-exp', name: 'Pengeluaran Lainnya', type: 'expense', icon: 'MoreHorizontal', color: '#64748B' },

  // Income
  { id: 'cat-salary', name: 'Gaji Bulanan', type: 'income', icon: 'BadgeDollarSign', color: '#10B981' },
  { id: 'cat-freelance', name: 'Freelance & Side Job', type: 'income', icon: 'Laptop', color: '#06B6D4' },
  { id: 'cat-business', name: 'Bisnis & Penjualan', type: 'income', icon: 'Store', color: '#8B5CF6' },
  { id: 'cat-investment-inc', name: 'Dividen & Investasi', type: 'income', icon: 'TrendingUp', color: '#10B981' },
  { id: 'cat-gift', name: 'Hadiah / THR / Bonus', type: 'income', icon: 'Gift', color: '#F59E0B' },
  { id: 'cat-other-inc', name: 'Pemasukan Lainnya', type: 'income', icon: 'MoreHorizontal', color: '#64748B' },
];

export const getInitialTransactions = (userId: string = 'demo-user'): Transaction[] => {
  const today = new Date();
  const getOffsetDate = (daysAgo: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().split('T')[0];
  };

  return [
    {
      id: 'tx-1',
      user_id: userId,
      type: 'income',
      amount: 12500000,
      category: 'Gaji Bulanan',
      category_icon: 'BadgeDollarSign',
      category_color: '#10B981',
      account_id: 'acc-bca',
      account_name: 'BCA Prioritas',
      date: getOffsetDate(5),
      time: '09:00',
      note: 'Gaji Pokok & Tunjangan Maret',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tx-2',
      user_id: userId,
      type: 'expense',
      amount: 45000,
      category: 'Makanan & Minuman',
      category_icon: 'UtensilsCrossed',
      category_color: '#F97316',
      account_id: 'acc-gopay',
      account_name: 'GoPay',
      date: getOffsetDate(0),
      time: '12:30',
      note: 'Makan siang Nasi Padang Komplit',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tx-3',
      user_id: userId,
      type: 'expense',
      amount: 150000,
      category: 'Transportasi & Bensin',
      category_icon: 'Car',
      category_color: '#3B82F6',
      account_id: 'acc-mandiri',
      account_name: 'Mandiri Livin',
      date: getOffsetDate(1),
      time: '08:15',
      note: 'Isi BBM Pertamax Full Tank',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tx-4',
      user_id: userId,
      type: 'expense',
      amount: 385000,
      category: 'Tagihan, Listrik & Wifi',
      category_icon: 'Zap',
      category_color: '#EAB308',
      account_id: 'acc-bca',
      account_name: 'BCA Prioritas',
      date: getOffsetDate(3),
      time: '19:40',
      note: 'Tagihan Internet IndiHome',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tx-5',
      user_id: userId,
      type: 'income',
      amount: 2500000,
      category: 'Freelance & Side Job',
      category_icon: 'Laptop',
      category_color: '#06B6D4',
      account_id: 'acc-bca',
      account_name: 'BCA Prioritas',
      date: getOffsetDate(2),
      time: '15:20',
      note: 'Pembayaran DP Web Development Klien',
      created_at: new Date().toISOString(),
    },
    {
      id: 'tx-6',
      user_id: userId,
      type: 'transfer',
      amount: 500000,
      category: 'Transfer Saldo',
      category_icon: 'ArrowRightLeft',
      category_color: '#6366F1',
      account_id: 'acc-bca',
      account_name: 'BCA Prioritas',
      to_account_id: 'acc-gopay',
      to_account_name: 'GoPay',
      date: getOffsetDate(2),
      time: '10:00',
      note: 'Top up GoPay mingguan',
      created_at: new Date().toISOString(),
    },
  ];
};
